<?php

namespace ContainerJpvmlBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditPasswordTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EditPasswordType' shared autowired service.
     *
     * @return \App\Form\EditPasswordType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EditPasswordType'] = new \App\Form\EditPasswordType();
    }
}
