<?php

namespace ContainerJpvmlBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartagePostTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PartagePostType' shared autowired service.
     *
     * @return \App\Form\PartagePostType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PartagePostType'] = new \App\Form\PartagePostType();
    }
}
