<?php

namespace ContainerJpvmlBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchPostTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SearchPostType' shared autowired service.
     *
     * @return \App\Form\SearchPostType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SearchPostType'] = new \App\Form\SearchPostType();
    }
}
