<?php

namespace ContainerJpvmlBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\UsersAuthenticator' shared autowired service.
     *
     * @return \App\Security\UsersAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\UsersAuthenticator'] = new \App\Security\UsersAuthenticator(($container->services['router'] ?? $container->getRouterService()), ($container->privates['session.flash_bag'] ?? $container->load('getSession_FlashBagService')));
    }
}
