<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJpvmlBG\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJpvmlBG/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJpvmlBG.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJpvmlBG\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJpvmlBG\App_KernelProdContainer([
    'container.build_hash' => 'JpvmlBG',
    'container.build_id' => 'b833eb83',
    'container.build_time' => 1658689465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJpvmlBG');
