<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/198.bef3af3b.js',
                '/build/981.baaa2d56.js',
                '/build/app.c71598d4.js',
            ],
            'css' => [
                '/build/app.37226bb6.css',
            ],
        ],
        'notyf' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/198.bef3af3b.js',
                '/build/notyf.60834e0f.js',
            ],
            'css' => [
                '/build/notyf.cd9b3258.css',
            ],
        ],
    ],
],

]];
