<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4lE7dwF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4lE7dwF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4lE7dwF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4lE7dwF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4lE7dwF\App_KernelDevDebugContainer([
    'container.build_hash' => '4lE7dwF',
    'container.build_id' => 'a74d3c1a',
    'container.build_time' => 1659710353,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4lE7dwF');
