<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7kx8LP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7kx8LP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7kx8LP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7kx8LP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7kx8LP\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7kx8LP',
    'container.build_id' => '8bef4eb8',
    'container.build_time' => 1660033240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7kx8LP');
