<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHOCDKEc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHOCDKEc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHOCDKEc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHOCDKEc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHOCDKEc\App_KernelDevDebugContainer([
    'container.build_hash' => 'HOCDKEc',
    'container.build_id' => 'f9d32d05',
    'container.build_time' => 1659967928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHOCDKEc');
