<?php

namespace ContainerHOCDKEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XeHqCUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._XeHqCU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._XeHqCU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'postsRepository' => 'App\\Repository\\PostsRepository',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);
    }
}
