<?php

namespace ContainerHOCDKEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartagePostTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PartagePostType' shared autowired service.
     *
     * @return \App\Form\PartagePostType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PartagePostType.php';

        return $container->privates['App\\Form\\PartagePostType'] = new \App\Form\PartagePostType();
    }
}
